/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RpFavoriteButton {
        /**
          * @default false
         */
        "favorite": boolean;
        /**
          * @default ''
         */
        "recipeTitle": string;
    }
    interface RpMealSlot {
        /**
          * @default ''
         */
        "day": string;
        /**
          * @default ''
         */
        "imageUrl": string;
        /**
          * @default ''
         */
        "recipeId": string;
        /**
          * @default ''
         */
        "recipeTitle": string;
    }
    interface RpRecipeCard {
        /**
          * @default false
         */
        "favorite": boolean;
        /**
          * @default ''
         */
        "imageUrl": string;
        /**
          * @default ''
         */
        "recipeId": string;
        /**
          * @default ''
         */
        "recipeTitle": string;
        /**
          * @default ''
         */
        "subtitle": string;
    }
    interface RpRecipeList {
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default []
         */
        "items": string[];
        /**
          * @default false
         */
        "ordered": boolean;
    }
    interface RpSearchInput {
        /**
          * @default 'Search recipes'
         */
        "label": string;
        /**
          * @default 'Search recipes'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface RpSelect {
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default []
         */
        "options": string[];
        /**
          * @default 'All options'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface RpTextInput {
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default false
         */
        "optional": boolean;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default 'text'
         */
        "type": 'text' | 'url';
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface RpFavoriteButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpFavoriteButtonElement;
}
export interface RpMealSlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpMealSlotElement;
}
export interface RpRecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpRecipeCardElement;
}
export interface RpSearchInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpSearchInputElement;
}
export interface RpSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpSelectElement;
}
export interface RpTextInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpTextInputElement;
}
declare global {
    interface HTMLRpFavoriteButtonElementEventMap {
        "favorite-toggle": { favorite: boolean };
    }
    interface HTMLRpFavoriteButtonElement extends Components.RpFavoriteButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpFavoriteButtonElementEventMap>(type: K, listener: (this: HTMLRpFavoriteButtonElement, ev: RpFavoriteButtonCustomEvent<HTMLRpFavoriteButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpFavoriteButtonElementEventMap>(type: K, listener: (this: HTMLRpFavoriteButtonElement, ev: RpFavoriteButtonCustomEvent<HTMLRpFavoriteButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpFavoriteButtonElement: {
        prototype: HTMLRpFavoriteButtonElement;
        new (): HTMLRpFavoriteButtonElement;
    };
    interface HTMLRpMealSlotElementEventMap {
        "meal-slot-select": { day: string };
        "meal-slot-remove": { day: string };
    }
    interface HTMLRpMealSlotElement extends Components.RpMealSlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpMealSlotElementEventMap>(type: K, listener: (this: HTMLRpMealSlotElement, ev: RpMealSlotCustomEvent<HTMLRpMealSlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpMealSlotElementEventMap>(type: K, listener: (this: HTMLRpMealSlotElement, ev: RpMealSlotCustomEvent<HTMLRpMealSlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpMealSlotElement: {
        prototype: HTMLRpMealSlotElement;
        new (): HTMLRpMealSlotElement;
    };
    interface HTMLRpRecipeCardElementEventMap {
        "recipe-select": { recipeId: string };
        "recipe-favorite-toggle": {
    recipeId: string;
    favorite: boolean;
  };
    }
    interface HTMLRpRecipeCardElement extends Components.RpRecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpRecipeCardElementEventMap>(type: K, listener: (this: HTMLRpRecipeCardElement, ev: RpRecipeCardCustomEvent<HTMLRpRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpRecipeCardElementEventMap>(type: K, listener: (this: HTMLRpRecipeCardElement, ev: RpRecipeCardCustomEvent<HTMLRpRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpRecipeCardElement: {
        prototype: HTMLRpRecipeCardElement;
        new (): HTMLRpRecipeCardElement;
    };
    interface HTMLRpRecipeListElement extends Components.RpRecipeList, HTMLStencilElement {
    }
    var HTMLRpRecipeListElement: {
        prototype: HTMLRpRecipeListElement;
        new (): HTMLRpRecipeListElement;
    };
    interface HTMLRpSearchInputElementEventMap {
        "value-change": { value: string };
    }
    interface HTMLRpSearchInputElement extends Components.RpSearchInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpSearchInputElementEventMap>(type: K, listener: (this: HTMLRpSearchInputElement, ev: RpSearchInputCustomEvent<HTMLRpSearchInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpSearchInputElementEventMap>(type: K, listener: (this: HTMLRpSearchInputElement, ev: RpSearchInputCustomEvent<HTMLRpSearchInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpSearchInputElement: {
        prototype: HTMLRpSearchInputElement;
        new (): HTMLRpSearchInputElement;
    };
    interface HTMLRpSelectElementEventMap {
        "value-change": { value: string };
    }
    interface HTMLRpSelectElement extends Components.RpSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpSelectElementEventMap>(type: K, listener: (this: HTMLRpSelectElement, ev: RpSelectCustomEvent<HTMLRpSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpSelectElementEventMap>(type: K, listener: (this: HTMLRpSelectElement, ev: RpSelectCustomEvent<HTMLRpSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpSelectElement: {
        prototype: HTMLRpSelectElement;
        new (): HTMLRpSelectElement;
    };
    interface HTMLRpTextInputElementEventMap {
        "value-change": { value: string };
    }
    interface HTMLRpTextInputElement extends Components.RpTextInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpTextInputElementEventMap>(type: K, listener: (this: HTMLRpTextInputElement, ev: RpTextInputCustomEvent<HTMLRpTextInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpTextInputElementEventMap>(type: K, listener: (this: HTMLRpTextInputElement, ev: RpTextInputCustomEvent<HTMLRpTextInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpTextInputElement: {
        prototype: HTMLRpTextInputElement;
        new (): HTMLRpTextInputElement;
    };
    interface HTMLElementTagNameMap {
        "rp-favorite-button": HTMLRpFavoriteButtonElement;
        "rp-meal-slot": HTMLRpMealSlotElement;
        "rp-recipe-card": HTMLRpRecipeCardElement;
        "rp-recipe-list": HTMLRpRecipeListElement;
        "rp-search-input": HTMLRpSearchInputElement;
        "rp-select": HTMLRpSelectElement;
        "rp-text-input": HTMLRpTextInputElement;
    }
}
declare namespace LocalJSX {
    interface RpFavoriteButton {
        /**
          * @default false
         */
        "favorite"?: boolean;
        "onFavorite-toggle"?: (event: RpFavoriteButtonCustomEvent<{ favorite: boolean }>) => void;
        /**
          * @default ''
         */
        "recipeTitle"?: string;
    }
    interface RpMealSlot {
        /**
          * @default ''
         */
        "day"?: string;
        /**
          * @default ''
         */
        "imageUrl"?: string;
        "onMeal-slot-remove"?: (event: RpMealSlotCustomEvent<{ day: string }>) => void;
        "onMeal-slot-select"?: (event: RpMealSlotCustomEvent<{ day: string }>) => void;
        /**
          * @default ''
         */
        "recipeId"?: string;
        /**
          * @default ''
         */
        "recipeTitle"?: string;
    }
    interface RpRecipeCard {
        /**
          * @default false
         */
        "favorite"?: boolean;
        /**
          * @default ''
         */
        "imageUrl"?: string;
        "onRecipe-favorite-toggle"?: (event: RpRecipeCardCustomEvent<{
    recipeId: string;
    favorite: boolean;
  }>) => void;
        "onRecipe-select"?: (event: RpRecipeCardCustomEvent<{ recipeId: string }>) => void;
        /**
          * @default ''
         */
        "recipeId"?: string;
        /**
          * @default ''
         */
        "recipeTitle"?: string;
        /**
          * @default ''
         */
        "subtitle"?: string;
    }
    interface RpRecipeList {
        /**
          * @default ''
         */
        "heading"?: string;
        /**
          * @default []
         */
        "items"?: string[];
        /**
          * @default false
         */
        "ordered"?: boolean;
    }
    interface RpSearchInput {
        /**
          * @default 'Search recipes'
         */
        "label"?: string;
        "onValue-change"?: (event: RpSearchInputCustomEvent<{ value: string }>) => void;
        /**
          * @default 'Search recipes'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface RpSelect {
        /**
          * @default ''
         */
        "label"?: string;
        "onValue-change"?: (event: RpSelectCustomEvent<{ value: string }>) => void;
        /**
          * @default []
         */
        "options"?: string[];
        /**
          * @default 'All options'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface RpTextInput {
        /**
          * @default ''
         */
        "label"?: string;
        "onValue-change"?: (event: RpTextInputCustomEvent<{ value: string }>) => void;
        /**
          * @default false
         */
        "optional"?: boolean;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default 'text'
         */
        "type"?: 'text' | 'url';
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface RpFavoriteButtonAttributes {
        "favorite": boolean;
        "recipeTitle": string;
    }
    interface RpMealSlotAttributes {
        "day": string;
        "recipeId": string;
        "recipeTitle": string;
        "imageUrl": string;
    }
    interface RpRecipeCardAttributes {
        "recipeId": string;
        "recipeTitle": string;
        "imageUrl": string;
        "subtitle": string;
        "favorite": boolean;
    }
    interface RpRecipeListAttributes {
        "heading": string;
        "ordered": boolean;
    }
    interface RpSearchInputAttributes {
        "label": string;
        "placeholder": string;
        "value": string;
    }
    interface RpSelectAttributes {
        "label": string;
        "placeholder": string;
        "value": string;
    }
    interface RpTextInputAttributes {
        "label": string;
        "placeholder": string;
        "type": 'text' | 'url';
        "value": string;
        "optional": boolean;
    }

    interface IntrinsicElements {
        "rp-favorite-button": Omit<RpFavoriteButton, keyof RpFavoriteButtonAttributes> & { [K in keyof RpFavoriteButton & keyof RpFavoriteButtonAttributes]?: RpFavoriteButton[K] } & { [K in keyof RpFavoriteButton & keyof RpFavoriteButtonAttributes as `attr:${K}`]?: RpFavoriteButtonAttributes[K] } & { [K in keyof RpFavoriteButton & keyof RpFavoriteButtonAttributes as `prop:${K}`]?: RpFavoriteButton[K] };
        "rp-meal-slot": Omit<RpMealSlot, keyof RpMealSlotAttributes> & { [K in keyof RpMealSlot & keyof RpMealSlotAttributes]?: RpMealSlot[K] } & { [K in keyof RpMealSlot & keyof RpMealSlotAttributes as `attr:${K}`]?: RpMealSlotAttributes[K] } & { [K in keyof RpMealSlot & keyof RpMealSlotAttributes as `prop:${K}`]?: RpMealSlot[K] };
        "rp-recipe-card": Omit<RpRecipeCard, keyof RpRecipeCardAttributes> & { [K in keyof RpRecipeCard & keyof RpRecipeCardAttributes]?: RpRecipeCard[K] } & { [K in keyof RpRecipeCard & keyof RpRecipeCardAttributes as `attr:${K}`]?: RpRecipeCardAttributes[K] } & { [K in keyof RpRecipeCard & keyof RpRecipeCardAttributes as `prop:${K}`]?: RpRecipeCard[K] };
        "rp-recipe-list": Omit<RpRecipeList, keyof RpRecipeListAttributes> & { [K in keyof RpRecipeList & keyof RpRecipeListAttributes]?: RpRecipeList[K] } & { [K in keyof RpRecipeList & keyof RpRecipeListAttributes as `attr:${K}`]?: RpRecipeListAttributes[K] } & { [K in keyof RpRecipeList & keyof RpRecipeListAttributes as `prop:${K}`]?: RpRecipeList[K] };
        "rp-search-input": Omit<RpSearchInput, keyof RpSearchInputAttributes> & { [K in keyof RpSearchInput & keyof RpSearchInputAttributes]?: RpSearchInput[K] } & { [K in keyof RpSearchInput & keyof RpSearchInputAttributes as `attr:${K}`]?: RpSearchInputAttributes[K] } & { [K in keyof RpSearchInput & keyof RpSearchInputAttributes as `prop:${K}`]?: RpSearchInput[K] };
        "rp-select": Omit<RpSelect, keyof RpSelectAttributes> & { [K in keyof RpSelect & keyof RpSelectAttributes]?: RpSelect[K] } & { [K in keyof RpSelect & keyof RpSelectAttributes as `attr:${K}`]?: RpSelectAttributes[K] } & { [K in keyof RpSelect & keyof RpSelectAttributes as `prop:${K}`]?: RpSelect[K] };
        "rp-text-input": Omit<RpTextInput, keyof RpTextInputAttributes> & { [K in keyof RpTextInput & keyof RpTextInputAttributes]?: RpTextInput[K] } & { [K in keyof RpTextInput & keyof RpTextInputAttributes as `attr:${K}`]?: RpTextInputAttributes[K] } & { [K in keyof RpTextInput & keyof RpTextInputAttributes as `prop:${K}`]?: RpTextInput[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rp-favorite-button": LocalJSX.IntrinsicElements["rp-favorite-button"] & JSXBase.HTMLAttributes<HTMLRpFavoriteButtonElement>;
            "rp-meal-slot": LocalJSX.IntrinsicElements["rp-meal-slot"] & JSXBase.HTMLAttributes<HTMLRpMealSlotElement>;
            "rp-recipe-card": LocalJSX.IntrinsicElements["rp-recipe-card"] & JSXBase.HTMLAttributes<HTMLRpRecipeCardElement>;
            "rp-recipe-list": LocalJSX.IntrinsicElements["rp-recipe-list"] & JSXBase.HTMLAttributes<HTMLRpRecipeListElement>;
            "rp-search-input": LocalJSX.IntrinsicElements["rp-search-input"] & JSXBase.HTMLAttributes<HTMLRpSearchInputElement>;
            "rp-select": LocalJSX.IntrinsicElements["rp-select"] & JSXBase.HTMLAttributes<HTMLRpSelectElement>;
            "rp-text-input": LocalJSX.IntrinsicElements["rp-text-input"] & JSXBase.HTMLAttributes<HTMLRpTextInputElement>;
        }
    }
}
